# Generated by Django 5.2.4 on 2025-07-27 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_payment_paid_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='paid_amount',
        ),
    ]
