# Generated by Django 5.2.4 on 2025-07-27 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_payment_paid_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='total_amount',
        ),
    ]
