# Generated by Django 5.2.4 on 2025-08-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='temp_field',
            field=models.CharField(default='', max_length=1),
        ),
    ]
