# Generated by Django 5.2.4 on 2025-08-03 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_user_temp_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='temp_field',
        ),
    ]
