# Generated by Django 5.2.4 on 2025-08-03 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_user_first_name_remove_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('provider', 'Provider'), ('administrator', 'Administrator')], max_length=20),
        ),
    ]
