# Generated by Django 5.2.4 on 2025-08-06 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_user_role'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booking',
            name='unique_student_room_dates',
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('booking_status__in', ['pending', 'approved', 'confirmed'])), fields=('student', 'room', 'check_in_date', 'check_out_date'), name='unique_student_room_dates'),
        ),
    ]
